### ISSUE TITLE
Installation issue: Bloomfilter

### ISSUE THREAD

**Issue by Astahlke** [bcgsc/LINKS#15]
Hi all, 

I'm trying to install LINKS for hybrid assembly of 10X and shotgun reads. As described below, I'm getting an error in trying to compile the Bloomfilter PERL module. Could it be due to a difference in capitalization, e.g. EXTERN.h and xsub.h?

From the installation instructions: 
"TO COMPILE, swig needs the following Perl5 headers:

#include "Extern.h"
#include "perl.h"
#include "XSUB.h"
If they are not located in /usr/lib64/perl5, you can run "perl -e 'use Config; print $Config{archlib};" to locate them."

Our cluster has those headers in lib64, but with different capitalization: EXTERN.h and xsub.h 

I tried using gcc versions 4.9.3 and 6.1.0 - see attached error logs. 

[error_gccv4.9.3.log](https://github.com/bcgsc/LINKS/files/1676168/error_gccv4.9.3.log)
[error_gccv6.1.0.log](https://github.com/bcgsc/LINKS/files/1676169/error_gccv6.1.0.log)

Thank you in advance!

Amanda

**Comment by warrenlr** [comment]
Hi Amanda,

From the feedback received from other users, this could be caused caused by incompatibility between the CORE and your current/default PERL. Refer to: https://github.com/bcgsc/LINKS/issues/9  and https://github.com/bcgsc/LINKS/issues/13

Is /usr/lib/perl5/core_perl/CORE the correct path matching your version of PERL?

Also, keep in mind you do not need the Bloom filter functionality if you are only going to use LINKS pipelined with ARCS or ARKS. I will send you a modified version of LINKS with the BF dependency removed (at your gmail).

Thanks
Rene

**Comment by mmokrejs** [comment]
Hi Rene,
  like Amanda I also realized now that https://github.com/bcgsc/LINKS/blob/master/README.md refers to `Extern.h` instead of `EXTERN.h`. Would you mind correcting that? Aren't both XSUB.h and EXTERN.h parts of a standard perl core?

  Also, could the installation tarball contain the usual Makefile.PL with an installation procedure installing into a typical system-wide location like other CPAN-based packages do? Unfortunately I am not up to make a pull request but I know what I am after. ;-) I would like to make a package of LINKS for Gentoo Linux and it seems I would have to hardcode all the compile commands into an installation script. Makefile.PL is the right way to do it. Thank you.

**Comment by warrenlr** [comment]
Thank you Martin, I will edit the README.
For the Makefile.PL, It is a good idea, although I strongly recommend users clone from https://github.com/bcgsc/btl_bloomfilter

The "lib" is included for users who may have issues compiling the btlbloom and may succeed in running LINKS using a pre-compiled version.

Due to other pressing commitments, I will not have time to look into this until DEC15 or so.
Thank you,
Rene
