### ISSUE TITLE
LINKS finding no kmer pairs on 10X data

### ISSUE THREAD

**Issue by enormandeau** [bcgsc/LINKS#32]
We have a fly genome assembled from PacBio that we treated with Tigmint and want to scaffold with ARKS and LINKS using 10X data.

I have run the commands presented in "infos_for_message_to_arks_and_links_authors.md". In this file, I also show the head/tail of important steps:
[infos_for_message_to_arks_and_links_authors.txt](https://github.com/bcgsc/LINKS/files/2699558/infos_for_message_to_arks_and_links_authors.txt)

Here are also both the ARKS and LINKS logs attached:
[log_arks_13956097.txt](https://github.com/bcgsc/LINKS/files/2699559/log_arks_13956097.txt)
[links_scaffolds_aa.log.txt](https://github.com/bcgsc/LINKS/files/2699560/links_scaffolds_aa.log.txt)

In the end, LINKS "Extracted 0 (zero) 30-mer pairs" and there is of course no scaffolding.

We are using 10X data to scaffold, which was prepared with longranger basic, ARKS 1.0.2, and LINKS 1.8.6 (I also tried 1.8.5).

I cannot track down the reason why zero 30-mer pairs are used. I would be much obliged if you could help me track my error.

**Comment by lcoombe** [comment]
Hi @enormandeau ,
I responded to your e-mail with some suggestions, but I'll post it here too. Just in case you have further ARKS-related questions, this sort of issue is better suited for the [ARKS repo](https://github.com/bcgsc/arks), just since this is a step in the ARKS pipeline.

Does the ARKS demo run successfully? (See Examples/arks_test-demo) 

Did you run the makeTSVfile.py script to generate the checkpoint file for LINKS? If so, at first glance, it looks to me like the naming of the checkpoint file (generated by makeTSVfile.py) isn't correct -- it must be \<prefix\>.tigpair_checkpoint.tsv, and \<prefix\> must be specified to the -b parameter of LINKS so it recognizes this input checkpoint file. That's important for LINKS to start at the right place -- you should see something like this in the output of LINKS:
```
Scaffolding mid-point files:
links_c5r0.05e30000-l5-a0.9.tigpair_checkpoint.tsv
links_c5r0.05e30000-l5-a0.9.simplepair_checkpoint.tsv
detected; LINKS will skip contig pairing and use info from files instead: Fri Feb 10 11:36:31 PST 2017
```

I suggest looking at our [ARKS test demo](https://github.com/bcgsc/arks/tree/master/Examples/arks_test-demo) and our [ARKS makefile](https://github.com/bcgsc/arks/blob/master/Examples/arks-make) which will help guide you through the steps required in the ARKS pipeline.

**Comment by enormandeau** [comment]
Hi  @lcoombe,

I ran the demo and it finished fine. I'm looking at the `pipeline_example.sh` script and the makefile itself and I am not sure how to use it with 10X data instead of mate pairs, for example.

My understanding so far is that I have to run the 10X reads through `longranger basic`, which I did, and then use the output fastq.gz file in the make file. **Do I have to change anything else?** It seems like maybe I need to use the `-D` option.

Thanks for your help

**Comment by lcoombe** [comment]
Hi @enormandeau ,

I'm glad you got the demo working OK!

The Makefile is already set up to use 10X data, so you don't have to change anything there. The ARKS+LINKS pipeline exclusively uses 10X data (as opposed to running LINKS alone, which you can use long reads or mate pair data for scaffolding). I know this can be a bit confusing, so just ask if you have more questions about what tool to use when!

Your understanding is correct - If you have your assembly and reads processed by ```longranger basic```, you are all ready to run ```arks-make```. You only need to include more options in your command if you wish to change any parameters from default. Running ```arks-make help``` will list all the options that you can add. For example:
```arks-make arks draft=mydraft reads=myreads threads=8 D=true```
will run ARKS with 8 threads, and enable distance estimation.

Hope that helps!

**Comment by enormandeau** [comment]
Hi @lcoombe,

ARKS and LINKS have now succesfully ran on out dataset. Thank you for the help.

**Comment by lcoombe** [comment]
Glad to hear you got it working!
