### ISSUE TITLE
PacBio scaffolding no change. Any recommendations ?

### ISSUE THREAD

**Issue by ptranvan** [bcgsc/LINKS#42]
Hello,

I have 2 species of 1.2G genome size that are quite fragmented (N50 species 1: 60k,  N50 species 2: 110k), made with illumina reads.

For species 1: I have 25X PacBio uncorrected

For species 2: I have 25X PacBio corrected by CANU.

I have tried only for species 2 for now and followed your recommendation about memory optimization ( I am limtied to 400GB RAM) : `-t 200 -d 500`

These parameters didn't change anything (or very minor).

Do you have any recommendations for these 2 cases ? 

Thanks a lot.

**Comment by warrenlr** [comment]
take a look at issues:

https://github.com/bcgsc/LINKS/issues/38
and
https://github.com/bcgsc/LINKS/issues/36

with -t200 -d500, do you maximize the RAM on your system?

From experience, -d500 won't do much. This is because your assembly, whether is it short or long read, has likely resolved all these distances in earlier steps (because either the fragment length/long read length is longer than 500)

I would run LINKS iteratively, -d 1000 -d2500 -d5000 -d7500 -d10000 are goo places to start, you can go longer if your pacbio reads allow (check the N50 of your sets). With each increased -d, you can decrease -t to maximize the number of kmer pairs.

**Comment by ptranvan** [comment]
Ok thank you.

Could the parameters be different and affect the final scaffolding according to corrected or un-corrected PacBio reads ? and coverage ?

**Comment by warrenlr** [comment]
for one thing, some parameters may have to be relaxed (eg. higher -t) for the corrected data set, as more kmer pairs will likely be extracted (ie kmer pairs extracted from the long reads are verified against a Bloom filter built out of your draft kmers, to help manage the RAM usage)

**Comment by ptranvan** [comment]
1) What does mean higher -t ? which value is considered as high ?

2) I tried different -k and it seems to be better. In one of the issue you mentioned, you recommend k19 for uncorrected reads and k26 for corrected reads. Is it still valid ?

3) The upper limit of -d is the N50 of long reads ?

**Comment by warrenlr** [comment]
Some answers...

>>What does mean higher -t ? which value is considered as high ?


You'll have to try different values.  @lcoombe  has some guidelines for spruce (-d, -t, -k with 5X spruce nanopore data.. equivalent of ~30X coverage of a 3Gbp genome).
-d 2500 -t 150 might be a good place to start but best to monitor the RAM usage.  In general, we find that LINKS will not handle bloated data structures exceeding 1TB of RAM and the process will become unstable. Again with spruce, we were able to iteratively scaffold many iterations and adjusting -t such that we would use 700-900 GB RAM on our systems.


>>I tried different -k and it seems to be better. In one of the issue you mentioned, you recommend k19 for uncorrected reads and k26 for corrected reads. Is it still valid ?

LINKS was developed with nanopore reads in mind. Because the error models are different with pacbio, you may be able to go higher (but can't say for sure). Again, you will have to test it out. May vary depending on your genome and size 


>>The upper limit of -d is the N50 of long reads ?

Not necessarily, we did try -k 100,000 on some assemblies, but typically cap it at 30,000 if your NG50 is 10-15kbp since you're return diminishes with increased -d (a read length distribution would be even more helpful than the N50 length in guiding your choice of distances)

**Comment by lcoombe** [comment]
Hi @ptranvan,

To give you a sense of the ballpark for `-t`, for 5X spruce nanopore data, I started at `-d 2500 -t 90`, and used `-k 23` - you could adjust `-t` higher depending on the specs of your machines. Overall I ran d=2500-10000 (step 2500), 15000-45000 (step 5000), and decreased `-t` by ~10 for the first few `-d` values, using `-t 1` for the last 5 `d` values. As @warrenlr mentioned, you can monitor the RAM usage and adjust accordingly.

**Comment by ptranvan** [comment]
Hi, 

Does the original contig size has an impact for the scaffolding ? Example, I have a lot of contigs < 1000bp (which are very short) for my illumina genome.

**Comment by warrenlr** [comment]
it plays a role, yes.

For one, these will be missed when using large kmer pair distances -d > contig lengths.  That's one of the reason why you want to start your iterative LINKS runs with lower -d first. 

By default, only sequences >=500bp are considered for scaffolding and this is controlled by -z

```-z  minimum contig length to consider for scaffolding (default -z 500, optional)```
